#!/usr/bin/env php
<?php

$opcodesFile = __DIR__ . '/opcodes.json';

$opcodes = json_decode(file_get_contents($opcodesFile), true);

foreach ($opcodes as $opcode)
{
    print_rust_opcode($opcode['opcode'], $opcode[''])
}

function print_rust_opcode($opcode, $bytes, $cycles)
{
    $output = <<< TXT
    fn nop(&mut self) {
        self.clock.m = $bytes;
        self.clock.t = $cycles;
    }

TXT;

}